/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package ci.palmafrique.vonabri.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// ANCIENNETE
	VIEW_ANCIENNETE("VIEW_ANCIENNETE"),	
	CREATE_ANCIENNETE("CREATE_ANCIENNETE"),
	UPDATE_ANCIENNETE("UPDATE_ANCIENNETE"),
	DELETE_ANCIENNETE("DELETE_ANCIENNETE"),
	// ANCIENNETE_TYPE
	VIEW_ANCIENNETE_TYPE("VIEW_ANCIENNETE_TYPE"),	
	CREATE_ANCIENNETE_TYPE("CREATE_ANCIENNETE_TYPE"),
	UPDATE_ANCIENNETE_TYPE("UPDATE_ANCIENNETE_TYPE"),
	DELETE_ANCIENNETE_TYPE("DELETE_ANCIENNETE_TYPE"),
	// DIRECTION
	VIEW_DIRECTION("VIEW_DIRECTION"),	
	CREATE_DIRECTION("CREATE_DIRECTION"),
	UPDATE_DIRECTION("UPDATE_DIRECTION"),
	DELETE_DIRECTION("DELETE_DIRECTION"),
	// ELEMENT
	VIEW_ELEMENT("VIEW_ELEMENT"),	
	CREATE_ELEMENT("CREATE_ELEMENT"),
	UPDATE_ELEMENT("UPDATE_ELEMENT"),
	DELETE_ELEMENT("DELETE_ELEMENT"),
	// ELEMENT_TYPE
	VIEW_ELEMENT_TYPE("VIEW_ELEMENT_TYPE"),	
	CREATE_ELEMENT_TYPE("CREATE_ELEMENT_TYPE"),
	UPDATE_ELEMENT_TYPE("UPDATE_ELEMENT_TYPE"),
	DELETE_ELEMENT_TYPE("DELETE_ELEMENT_TYPE"),
	// EMPLOYEUR
	VIEW_EMPLOYEUR("VIEW_EMPLOYEUR"),	
	CREATE_EMPLOYEUR("CREATE_EMPLOYEUR"),
	UPDATE_EMPLOYEUR("UPDATE_EMPLOYEUR"),
	DELETE_EMPLOYEUR("DELETE_EMPLOYEUR"),
	// ETHNIE
	VIEW_ETHNIE("VIEW_ETHNIE"),	
	CREATE_ETHNIE("CREATE_ETHNIE"),
	UPDATE_ETHNIE("UPDATE_ETHNIE"),
	DELETE_ETHNIE("DELETE_ETHNIE"),
	// FONCTION
	VIEW_FONCTION("VIEW_FONCTION"),	
	CREATE_FONCTION("CREATE_FONCTION"),
	UPDATE_FONCTION("UPDATE_FONCTION"),
	DELETE_FONCTION("DELETE_FONCTION"),
	// FONCTIONNALITE
	VIEW_FONCTIONNALITE("VIEW_FONCTIONNALITE"),	
	CREATE_FONCTIONNALITE("CREATE_FONCTIONNALITE"),
	UPDATE_FONCTIONNALITE("UPDATE_FONCTIONNALITE"),
	DELETE_FONCTIONNALITE("DELETE_FONCTIONNALITE"),
	// GESTION_DE_BIEN
	VIEW_GESTION_DE_BIEN("VIEW_GESTION_DE_BIEN"),	
	CREATE_GESTION_DE_BIEN("CREATE_GESTION_DE_BIEN"),
	UPDATE_GESTION_DE_BIEN("UPDATE_GESTION_DE_BIEN"),
	DELETE_GESTION_DE_BIEN("DELETE_GESTION_DE_BIEN"),
	// NATIONNALITE
	VIEW_NATIONNALITE("VIEW_NATIONNALITE"),	
	CREATE_NATIONNALITE("CREATE_NATIONNALITE"),
	UPDATE_NATIONNALITE("UPDATE_NATIONNALITE"),
	DELETE_NATIONNALITE("DELETE_NATIONNALITE"),
	// POSTE_DE_TRAVAIL
	VIEW_POSTE_DE_TRAVAIL("VIEW_POSTE_DE_TRAVAIL"),	
	CREATE_POSTE_DE_TRAVAIL("CREATE_POSTE_DE_TRAVAIL"),
	UPDATE_POSTE_DE_TRAVAIL("UPDATE_POSTE_DE_TRAVAIL"),
	DELETE_POSTE_DE_TRAVAIL("DELETE_POSTE_DE_TRAVAIL"),
	// PROFIL
	VIEW_PROFIL("VIEW_PROFIL"),	
	CREATE_PROFIL("CREATE_PROFIL"),
	UPDATE_PROFIL("UPDATE_PROFIL"),
	DELETE_PROFIL("DELETE_PROFIL"),
	// PROFIL_FONCTIONNALITE
	VIEW_PROFIL_FONCTIONNALITE("VIEW_PROFIL_FONCTIONNALITE"),	
	CREATE_PROFIL_FONCTIONNALITE("CREATE_PROFIL_FONCTIONNALITE"),
	UPDATE_PROFIL_FONCTIONNALITE("UPDATE_PROFIL_FONCTIONNALITE"),
	DELETE_PROFIL_FONCTIONNALITE("DELETE_PROFIL_FONCTIONNALITE"),
	// REGIME
	VIEW_REGIME("VIEW_REGIME"),	
	CREATE_REGIME("CREATE_REGIME"),
	UPDATE_REGIME("UPDATE_REGIME"),
	DELETE_REGIME("DELETE_REGIME"),
	// SITE
	VIEW_SITE("VIEW_SITE"),	
	CREATE_SITE("CREATE_SITE"),
	UPDATE_SITE("UPDATE_SITE"),
	DELETE_SITE("DELETE_SITE"),
	// SOUS_POSTE_DE_TRAVAIL
	VIEW_SOUS_POSTE_DE_TRAVAIL("VIEW_SOUS_POSTE_DE_TRAVAIL"),	
	CREATE_SOUS_POSTE_DE_TRAVAIL("CREATE_SOUS_POSTE_DE_TRAVAIL"),
	UPDATE_SOUS_POSTE_DE_TRAVAIL("UPDATE_SOUS_POSTE_DE_TRAVAIL"),
	DELETE_SOUS_POSTE_DE_TRAVAIL("DELETE_SOUS_POSTE_DE_TRAVAIL"),
	// SOUS_SITE
	VIEW_SOUS_SITE("VIEW_SOUS_SITE"),	
	CREATE_SOUS_SITE("CREATE_SOUS_SITE"),
	UPDATE_SOUS_SITE("UPDATE_SOUS_SITE"),
	DELETE_SOUS_SITE("DELETE_SOUS_SITE"),
	// STATUT
	VIEW_STATUT("VIEW_STATUT"),	
	CREATE_STATUT("CREATE_STATUT"),
	UPDATE_STATUT("UPDATE_STATUT"),
	DELETE_STATUT("DELETE_STATUT"),
	// STATUT_MATRIMONIAL
	VIEW_STATUT_MATRIMONIAL("VIEW_STATUT_MATRIMONIAL"),	
	CREATE_STATUT_MATRIMONIAL("CREATE_STATUT_MATRIMONIAL"),
	UPDATE_STATUT_MATRIMONIAL("UPDATE_STATUT_MATRIMONIAL"),
	DELETE_STATUT_MATRIMONIAL("DELETE_STATUT_MATRIMONIAL"),
	// TRAVAILLEUR
	VIEW_TRAVAILLEUR("VIEW_TRAVAILLEUR"),	
	CREATE_TRAVAILLEUR("CREATE_TRAVAILLEUR"),
	UPDATE_TRAVAILLEUR("UPDATE_TRAVAILLEUR"),
	DELETE_TRAVAILLEUR("DELETE_TRAVAILLEUR"),
	// TRAVAILLEUR_NATIONNALITE
	VIEW_TRAVAILLEUR_NATIONNALITE("VIEW_TRAVAILLEUR_NATIONNALITE"),	
	CREATE_TRAVAILLEUR_NATIONNALITE("CREATE_TRAVAILLEUR_NATIONNALITE"),
	UPDATE_TRAVAILLEUR_NATIONNALITE("UPDATE_TRAVAILLEUR_NATIONNALITE"),
	DELETE_TRAVAILLEUR_NATIONNALITE("DELETE_TRAVAILLEUR_NATIONNALITE"),
	// TYPE_MARIAGE
	VIEW_TYPE_MARIAGE("VIEW_TYPE_MARIAGE"),	
	CREATE_TYPE_MARIAGE("CREATE_TYPE_MARIAGE"),
	UPDATE_TYPE_MARIAGE("UPDATE_TYPE_MARIAGE"),
	DELETE_TYPE_MARIAGE("DELETE_TYPE_MARIAGE"),
	// USER
	VIEW_USER("VIEW_USER"),	
	CREATE_USER("CREATE_USER"),
	UPDATE_USER("UPDATE_USER"),
	DELETE_USER("DELETE_USER"),
	RESET_PASSWORD_USER("RESET_PASSWORD_USER"),

	// USER_TYPE
	VIEW_USER_TYPE("VIEW_USER_TYPE"),	
	CREATE_USER_TYPE("CREATE_USER_TYPE"),
	UPDATE_USER_TYPE("UPDATE_USER_TYPE"),
	DELETE_USER_TYPE("DELETE_USER_TYPE"),
	 
	// PAYS
	VIEW_PAYS("VIEW_PAYS"),	
	CREATE_PAYS("CREATE_PAYS"),
	UPDATE_PAYS("UPDATE_PAYS"),
	DELETE_PAYS("DELETE_PAYS"),
	
		// CIVILITE
		VIEW_CIVILITE("VIEW_CIVILITE"),	
		CREATE_CIVILITE("CREATE_CIVILITE"),
		UPDATE_CIVILITE("UPDATE_CIVILITE"),
		DELETE_CIVILITE("DELETE_CIVILITE");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
