/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package ci.palmafrique.vonabri.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// ELEMENT
	VIEW_ELEMENT("VIEW_ELEMENT"),	
	CREATE_ELEMENT("CREATE_ELEMENT"),
	UPDATE_ELEMENT("UPDATE_ELEMENT"),
	DELETE_ELEMENT("DELETE_ELEMENT"),
	// ELEMENT_TYPE
	VIEW_ELEMENT_TYPE("VIEW_ELEMENT_TYPE"),	
	CREATE_ELEMENT_TYPE("CREATE_ELEMENT_TYPE"),
	UPDATE_ELEMENT_TYPE("UPDATE_ELEMENT_TYPE"),
	DELETE_ELEMENT_TYPE("DELETE_ELEMENT_TYPE"),
	// FONCTIONNALITE
	VIEW_FONCTIONNALITE("VIEW_FONCTIONNALITE"),	
	CREATE_FONCTIONNALITE("CREATE_FONCTIONNALITE"),
	UPDATE_FONCTIONNALITE("UPDATE_FONCTIONNALITE"),
	DELETE_FONCTIONNALITE("DELETE_FONCTIONNALITE"),
	// PROFIL
	VIEW_PROFIL("VIEW_PROFIL"),	
	CREATE_PROFIL("CREATE_PROFIL"),
	UPDATE_PROFIL("UPDATE_PROFIL"),
	DELETE_PROFIL("DELETE_PROFIL"),
	// PROFIL_FONCTIONNALITE
	VIEW_PROFIL_FONCTIONNALITE("VIEW_PROFIL_FONCTIONNALITE"),	
	CREATE_PROFIL_FONCTIONNALITE("CREATE_PROFIL_FONCTIONNALITE"),
	UPDATE_PROFIL_FONCTIONNALITE("UPDATE_PROFIL_FONCTIONNALITE"),
	DELETE_PROFIL_FONCTIONNALITE("DELETE_PROFIL_FONCTIONNALITE"),
	// USER
	VIEW_USER("VIEW_USER"),	
	CREATE_USER("CREATE_USER"),
	UPDATE_USER("UPDATE_USER"),
	DELETE_USER("DELETE_USER"),
	RESET_PASSWORD_USER("RESET_PASSWORD_USER"),

	// USER_TYPE
	VIEW_USER_TYPE("VIEW_USER_TYPE"),	
	CREATE_USER_TYPE("CREATE_USER_TYPE"),
	UPDATE_USER_TYPE("UPDATE_USER_TYPE"),
	DELETE_USER_TYPE("DELETE_USER_TYPE");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
