/*
 * Created on 2022-07-27 ( Time 01:31:44 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.palmafrique.vonabri.dao.entity;

import java.io.Serializable;

import lombok.*;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "production"
 *
 * @author Telosys Tools Generator
 *
 */
@Data
@ToString
@Entity
@Table(name="production" )
public class Production implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date")
    private Date       date         ;

    @Column(name="acidite_huile")
    private Double     aciditeHuile ;

    @Column(name="regimes_mal_egra")
    private Double     regimesMalEgra ;

    @Column(name="cages_carreau", length=255)
    private String     cagesCarreau ;

    @Column(name="pi")
    private Double     pi           ;

    @Column(name="pvp")
    private Double     pvp          ;

    @Column(name="sortie_huile")
    private Double     sortieHuile  ;

    @Column(name="sortie_palmiste")
    private Double     sortiePalmiste ;

    @Column(name="stok_palmiste")
    private Double     stokPalmiste ;

    @Column(name="regimes_traiter")
    private Double     regimesTraiter ;

    @Column(name="production_huile")
    private Double     productionHuile ;

    @Column(name="production_palmiste")
    private Double     productionPalmiste ;

    @Column(name="taux_extraction_huile")
    private Double     tauxExtractionHuile ;

    @Column(name="taux_extraction_palmiste")
    private Double     tauxExtractionPalmiste ;

    @Column(name="sortie_huile_de_sarci")
    private Double     sortieHuileDeSarci ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at")
    private Date       createdAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deleted_at")
    private Date       deletedAt    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at")
    private Date       updatedAt    ;

    @Column(name="created_by")
    private Integer    createdBy    ;

    @Column(name="updated_by")
    private Integer    updatedBy    ;

    @Column(name="deleted_by")
    private Integer    deletedBy    ;

    @Column(name="is_deleted")
    private Boolean    isDeleted    ;

	// "siteId" (column "site_id") is not defined by itself because used as FK in a link 

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="site_id", referencedColumnName="id")
    private Site site        ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Production() {
		super();
    }
    
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public java.lang.Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
